# Generated by Django 5.1.3 on 2024-11-11 00:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=users.models.generate_unique_username, max_length=30, unique=True),
        ),
    ]
