# Generated by Django 5.1.3 on 2024-11-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unique_code',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
